// 06、React/源码/dev/02_src_hello_react/App.jsx
/*
 * @Author: your name
 * @Date: 2021-12-23 10:41:42
 * @LastEditTime: 2021-12-27 19:38:12
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: /06、React/源码/dev/02_src_hello_react/App.jsx
 */
//创建“外壳”组件App
import React,{Component} from 'react'

//创建并暴露App组件
export default class App extends Component{
	render(){
		return (
			<div>
			app
			</div>
		)
	}
}

// 05、Vue/element/src/App.vue
<!--
 * @Author: your name
 * @Date: 2021-12-10 16:17:58
 * @LastEditTime: 2021-12-12 11:29:35
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: /Full-stack/05、Vue/element/src/App.vue
-->
<template>
  <div id="app">
  <router-view></router-view>
  </div>
</template>

<style lang="scss">
body,html{
  margin: 0;
  padding: 0;
}
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;

}

#nav {
  padding: 30px;

  a {
    font-weight: bold;
    color: #2c3e50;

    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>
